# Generated by Django 5.1.5 on 2025-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_alter_sign_latitude_alter_sign_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sign',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
